### PR TITLE
Update README

### PR DESCRIPTION
**Pull request by Powerlated**
As a result of further development, the included README is now obsolete.

### CODE REVIEW

**Comment by wheremyfoodat** [comment]
@Powerlated We regret to inform you that your contribution is in violation of several Beeg Advanced/yes$wool behavioral and stylistic guidelines. If you deem this choice erroneous, feel free to contact us via Discord, Github, or the following email address:

**Comment by wheremyfoodat** [comment]
I've been bamboozled

**Comment by wheremyfoodat** [comment]
You need medical help

**Comment by Powerlated** [comment]
firkc uyo

**Pull request closed without merging**
